[utils] Timer: Add missing include for sstream
Fixes build issue on FreeBSD 14.0

error: implicit instantiation of undefined template 'std::basic_ostringstream<char>